--CREATE TABLE Products (
--    id int not null,
--    name nvarchar(128),
--    description varchar(512)
--)
--
--insert into Products (id, name, description)
--values(1,'FP_Pen','Fountain Pen')
--values(2,'BP_Pen','Ballpoint Pen')
--values(3,'Pencil','Wooden Pencil')
--values(4,'S_Pencil','Stacked Pencil'),
--values(5,'Mouse','Computer mouse(not a living mouse)');
